# Generated by Django 2.2 on 2019-06-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('opening_stock', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
