# Generated by Django 2.2 on 2019-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_item',
            name='unit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
