# Generated by Django 2.2 on 2019-06-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20190601_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_item',
        ),
    ]
