# Generated by Django 2.2 on 2019-06-02 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_add_item_unit'),
        ('transaction', '0003_delete_add_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_title', models.CharField(max_length=100, unique=True)),
                ('parent_id', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('phone_no', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('ntn', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('footer_description', models.TextField()),
                ('payment_method', models.CharField(max_length=100)),
                ('account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.ChartOfAccount')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Add_item')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.PurchaseHeader')),
            ],
        ),
    ]
