# Generated by Django 2.2 on 2019-06-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_company_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='price',
            new_name='height',
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='square_fit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
